#ifndef SPIKE_VP_CONFIG_H
#define SPIKE_VP_CONFIG_H

#define SPIKEVP_VERSION_STRING  "1"
#define SPIKEVP_CPU_DEFCLK (100 * vcml::MHz)

#define SPIKEVP_RESETVEC (0x80000000)

/* Memory map */
#define SPIKEVP_MEM_ADDR (0x80000000)
#define SPIKEVP_MEM_SIZE (0x1000000000) // 4 GB
#define SPIKEVP_MEM_END  (SPIKEVP_MEM_ADDR + SPIKEVP_MEM_SIZE - 1)

#endif
